// appErrorCodes.ts
export const appErrorCodes = {
  PAYMENT_METHOD_NOT_FOUND: 'PAYMENT_METHOD_NOT_FOUND',
  PAYOUT_METHOD_NOT_FOUND: 'PAYOUT_METHOD_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
  CONSULTANT_NOT_FOUND: 'CONSULTANT_NOT_FOUND',
  // Add more as needed...
} as const;
