/* error codes have to be unique in order to find the problem in a fast way with the debugger */
export const AppErrorCodes = {
  MOCK_ERROR: 'MOCK_ERROR',
  REQUEST_VALIDATION_ERROR: 'REQUEST_VALIDATION_ERROR',
  CONFIG_VALIDATION_ERROR: 'CONFIG_VALIDATION_ERROR',
  UPDATE_PAYMENT_METHOD_NOT_FOUND: 'UPDATE_PAYMENT_METHOD_NOT_FOUND',
  UPDATE_PAYMENT_METHOD_WRONG_USER_ID: 'UPDATE_PAYMENT_METHOD_WRONG_USER_ID',
  GET_PAYMENT_METHODS_USER_NOT_FOUND: 'GET_PAYMENT_METHODS_USER_NOT_FOUND',
  ADD_PAYMENT_METHOD_USER_NOT_FOUND: 'ADD_PAYMENT_METHOD_USER_NOT_FOUND',
  DELETE_PAYMENT_METHOD_NOT_FOUND: 'DELETE_PAYMENT_METHOD_NOT_FOUND',
  DELETE_PAYMENT_METHOD_WRONG_USER_ID: 'DELETE_PAYMENT_METHOD_WRONG_USER_ID',
  UPDATE_WITHDRAW_METHOD_WRONG_USER_ID: 'UPDATE_WITHDRAW_METHOD_WRONG_USER_ID',
  UPDATE_WITHDRAW_METHOD_NOT_FOUND: 'UPDATE_WITHDRAW_METHOD_NOT_FOUND',
  DELETE_WITHDRAW_METHOD_NOT_FOUND: 'DELETE_WITHDRAW_METHOD_NOT_FOUND',
  DELETE_WITHDRAW_METHOD_WRONG_USER_ID: 'DELETE_WITHDRAW_METHOD_WRONG_USER_ID',
  GET_WITHDRAW_METHODS_USER_NOT_FOUND: 'GET_WITHDRAW_METHODS_USER_NOT_FOUND',
  ADD_WITHDRAW_METHODS_USER_NOT_FOUND: 'ADD_WITHDRAW_METHODS_USER_NOT_FOUND',
} as const;

export type AppErrorCode = (typeof AppErrorCodes)[keyof typeof AppErrorCodes];
