// events/names/send.ts
export const sendEventsNames = {
  SEND_NOTIFICATION: 'SEND_NOTIFICATION',
  SEND_NOTIFICATION_FUNDUMENTAL: 'SEND_NOTIFICATION_FUNDUMENTAL',
  SEND_PINCODE_EMAIL: 'SEND_PINCODE_EMAIL',
  DELIVERY_SUCCEEDED: 'DELIVERY_SUCCEEDED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
} as const;
