apiVersion: apps/v1
kind: Deployment
metadata:
  name: ava-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ava
  template:
    metadata:
      labels:
        app: ava
      annotations:
        secret_checksum: "BGbEcrob5qNXALGGfeolK8kU5G67aFIs8KLjucboaT4="
    spec:
      containers:
      - name: ava
        image: ava
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: ava-secret
