apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
      annotations:
        secret_checksum: "BGbEcrob5qNXALGGfeolK8kU5G67aFIs8KLjucboaT4="
    spec:
      containers:
      - name: booking
        image: booking
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: booking-secret
