apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: chat
        ports:
        - containerPort: 3000
        - containerPort: 9229

