apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
      annotations:
        secret_checksum: "JeI7/aZAX4rorXwLLfRu5XF5y0TMe1EkX8tVAxs1x2c="
    spec:
      containers:
      - name: chat
        image: chat
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: chat-secret
