apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultant-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultant
  template:
    metadata:
      labels:
        app: consultant
      annotations:
        secret_checksum: "6IrdnEphwV1MZ9LoYLXHP8GIK7udB4lsCwXX5kw9SJQ="
    spec:
      containers:
      - name: consultant
        image: consultant
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: consultant-secret
