apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
      - name: notify
        image: notify
        ports:
        - containerPort: 3000
        - containerPort: 9229

