apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
      annotations:
        secret_checksum: "5RGatWyACTDAA4ZO9ygtpYqEfsAUc9V8DCSrC/1rfgk="
    spec:
      containers:
      - name: notify
        image: notify
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: notify-secret
