apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: rating
        ports:
        - containerPort: 3000
        - containerPort: 9229

