apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
      annotations:
        secret_checksum: "ept4ju6Sequ+slH+wSyu0R1xl/wnIc0678nY+LKK/t4="
    spec:
      containers:
      - name: search
        image: search
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: search-secret
