apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send
  template:
    metadata:
      labels:
        app: send
      annotations:
        secret_checksum: "B7bMSZd8wg2qdRQiru5QVA7b8jwP0VyUynIVHSzyFOo="
    spec:
      containers:
      - name: send
        image: send
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: send-secret
