apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send
  template:
    metadata:
      labels:
        app: send
    spec:
      containers:
      - name: send
        image: send
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: send-secret
