apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signup
  template:
    metadata:
      labels:
        app: signup
      annotations:
        secret_checksum: "1BXHAPU2KOUQ0Kg/QjFKw39rQVPR2pVIELb7UVNpW08="
    spec:
      containers:
      - name: signup
        image: signup
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: signup-secret
