apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
      annotations:
        secret_checksum: "BGbEcrob5qNXALGGfeolK8kU5G67aFIs8KLjucboaT4="
    spec:
      containers:
      - name: socket
        image: socket
        ports:
        - containerPort: 3000
        - containerPort: 9229
        envFrom:
        - secretRef:
            name: socket-secret
