apiVersion: apps/v1
kind: Deployment
metadata:
  name: sockets-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sockets
  template:
    metadata:
      labels:
        app: sockets
    spec:
      containers:
      - name: sockets
        image: sockets
        ports:
        - containerPort: 3000
        - containerPort: 9229

