// appErrorCodes.ts
export const appErrorCodes = {
  BLOCK_NOT_AVAILABLE: 'BLOCK_NOT_AVAILABLE',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
  INVALID_BOOKING_STATUS: 'INVALID_BOOKING_STATUS',
} as const;
