export const appErrorCodes = {
  INVALID_CONNECTION_TYPE: 'INVALID_CONNECTION_TYPE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CONSULTANT_NOT_FOUND: 'CONSULTANT_NOT_FOUND',
} as const;
