export const chatEventsNames = {
  MESSAGE_SENT: 'MESSAGE_SENT',
  CHAT_CREATED: 'CHAT_CREATED',
  CHAT_UPDATED: 'CHAT_UPDATED',
  GROUP_CREATED: 'GROUP_CREATED',
  GROUP_UPDATED: 'GROUP_UPDATED',
  USER_JOINED_GROUP: 'USER_JOINED_GROUP',
  USER_LEFT_GROUP: 'USER_LEFT_GROUP',
  MESSAGE_READ: 'MESSAGE_READ',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
} as const;
