export const paymentEventsNames = {
  PAYMENT_METHOD_ADDED_AND_VERIFIED: 'PAYMENT_METHOD_ADDED_AND_VERIFIED',
  PAYMENT_METHOD_DELETED_OR_DECLINED: 'PAYMENT_METHOD_DELETED',
  PAYMENT_METHOD_UPDATED: 'PAYMENT_METHOD_UPDATED',
  WITHDRAW_METHOD_ADDED_AND_VERIFIED: 'WITHDRAW_METHOD_ADDED_AND_VERIFIED',
  WITHDRAW_METHOD_DELETED_OR_DECLINED: 'WITHDRAW_METHOD_DELETED',
  WITHDRAW_METHOD_UPDATED: 'WITHDRAW_METHOD_UPDATED',
  SUCCESSFUL_PAYMENT: 'SUCCESSFUL_PAYMENT',
  FAILED_PAYMENT: 'FAILED_PAYMENT',
  SUCCESSFUL_WITHDRAW: 'SUCCESSFUL_WITHDRAW',
  FAILED_WITHDRAW: 'FAILED_WITHDRAW',
} as const;
