// names.ts
export const signupEventsNames = {
  SEND_PINCODE_EMAIL: 'SEND_PINCODE_EMAIL',
  USER_CREATED: 'USER_CREATED',
  NEW_PASSWORD_SET: 'NEW_PASSWORD_SET',
  OAUTH_LINKED: 'OAUTH_LINKED',
  AUTH_METHOD_ADDED: 'AUTH_METHOD_ADDED',
} as const;
