// appErrorCodes.ts

export const appErrorCodes = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_NOTIFICATION_TYPE: 'INVALID_NOTIFICATION_TYPE',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  NOTIFICATION_SCHEDULING_FAILED: 'NOTIFICATION_SCHEDULING_FAILED',
  // Add more as needed...
} as const;
